customhost = "database-1.c24yyu4zym88.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yeohxiongkeat-busket"
customregion = "us-east-1"
